apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-obj-dev
spec:
  replicas: 1
  selector:
    app: k8s-obj-dev
  template:
    metadata:
      labels:
        app: k8s-obj-dev 
    spec:
      containers:
      - image: 172.255.4.100:5000/k8s-obj:v1.0
        name: uwsgi
        securityContext:
          privileged: true
        ports:
        - name: uwsgiport
          containerPort: 9090
      nodeSelector:
        zone: north
